const T=window.OPENX_TOKENS;
const rgb=hex=>hex.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16));
const luminance=hex=>rgb(hex).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const ink=hex=>contrast(hex,'#0B0B0B')>contrast(hex,'#FFFFFF')?'#0B0B0B':'#FFFFFF';
const chip=hex=>`<span class="color-value"><i style="--chip:${hex}" aria-hidden="true"></i>${hex}</span>`;
document.getElementById('neutral-scale').innerHTML=Object.entries(T.neutral).sort(([a],[b])=>Number(a)-Number(b)).map(([name,hex])=>`<button class="neutral-swatch" data-copy="${hex}" style="--swatch:${hex};--ink:${ink(hex)}" aria-label="复制 Neutral ${name} ${hex}"><span>NEUTRAL ${name}</span><b>${hex}</b></button>`).join('');
const roles=[['canvas','页面背景','整个页面的基础画布'],['navigation','导航表面','页头、侧栏'],['surface','内容卡面','资产、表单、列表容器'],['raised','浮层表面','弹窗、下拉菜单'],['hover','中性悬停','列表、次要按钮'],['selected','中性选中','导航、标签、选择项'],['border','分隔边框','非必要识别的卡片边界 / 分隔线'],['borderStrong','控件默认边框','浅灰 / 深灰细线，用于可编辑字段与描边控件'],['borderHover','控件悬停边框','指针进入时略微加强'],['dangerBorder','错误边框','柔和状态线，配合清楚的错误文字'],['text','主要文字','标题、金额、关键标签'],['body','正文','描述、数据正文'],['muted','辅助文字','日期、单位、说明'],['disabled','禁用内容','不可操作控件'],['focus','键盘焦点','2px 焦点环']];
document.getElementById('theme-rows').innerHTML=roles.map(([k,label,use])=>`<tr><td>${label}</td><td>${chip(T.light[k])}</td><td>${chip(T.dark[k])}</td><td>${use}</td></tr>`).join('');
const siteArrow="<span class=\"site-arrow\" aria-hidden=\"true\"><svg class=\"arrow-a\" viewBox=\"0 0 16 16\" fill=\"none\"><path d=\"M4 12L12 4M12 4H6M12 4V10\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg><svg class=\"arrow-b\" viewBox=\"0 0 16 16\" fill=\"none\"><path d=\"M4 12L12 4M12 4H6M12 4V10\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg></span>";
document.getElementById('brand-states').innerHTML=[['Default / 默认','','#FF8200','原站橙色胶囊'],['Hover / 悬停','force-hover','brightness(1.12)','提亮 · 箭头沿 45° 滑动'],['Pressed / 按下','force-pressed','scale(0.97)','保持悬停样式 · 缩小反馈']].map(([name,variant,rule,note])=>`<div class="brand-state"><div class="state-caption"><span>${name}</span><b>${rule}</b></div><div class="brand-state-preview"><button class="site-btn site-orange ${variant}">开始使用${siteArrow}</button></div><span class="state-purpose">${note}</span></div>`).join('');
const connectionCases=[
 {name:'主账户',method:'API 连接',state:'已连接',kind:'ready',detail:'读取与交易权限正常',explain:'账户已连接，读取与交易权限正常。连接状态和授权范围分别呈现，便于核对。'},
 {name:'备用账户',method:'UID 绑定',state:'待验证',kind:'pending',detail:'等待账户验证完成',explain:'绑定信息已记录，正在等待账户验证。等待状态使用中性图标和文字。'},
 {name:'量化账户',method:'API 连接',state:'需重新授权',kind:'error',detail:'原授权已失效',explain:'连接的 API 授权已失效，需要重新授权。异常原因靠近状态显示，并保留明确的下一步操作。'},
 {name:'策略账户',method:'API 连接',state:'连接中',kind:'progress',detail:'正在确认授权信息',explain:'正在确认账户授权信息。处理中只强调进度图标，账户名称与说明保持稳定。'}
];
const statusIcon=kind=>'<svg viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.4">'+({ready:'<circle cx="8" cy="8" r="5.7"/><path d="m5 8 2 2 4-4"/>',pending:'<circle cx="8" cy="8" r="5.7" stroke-dasharray="2 2"/>',error:'<circle cx="8" cy="8" r="5.7"/><path d="M8 4.8v4.4m0 1.3v.8"/>',progress:'<circle cx="8" cy="8" r="5.7" opacity=".3"/><path d="M8 2.3a5.7 5.7 0 0 1 5.7 5.7"/>'}[kind])+'</svg>';
document.getElementById('semantic-grid').innerHTML=`<div class="connection-example" data-theme="light" id="connection-example"><div class="connection-toolbar"><div><h4>交易所连接</h4><span>账户、授权状态与说明</span></div><div class="connection-theme" role="group" aria-label="连接列表主题"><button data-list-theme="light" aria-pressed="true">浅色</button><button data-list-theme="dark" aria-pressed="false">深色</button></div></div><div class="connection-column-head" aria-hidden="true"><span>账户</span><span>连接状态</span><span>说明</span><span>操作</span></div><ul class="connection-list">${connectionCases.map((item,i)=>`<li><div class="connection-identity"><b>${item.name}</b><span>${item.method}</span></div><div class="connection-status ${item.kind}">${statusIcon(item.kind)}<span>${item.state}</span></div><span class="connection-detail">${item.detail}</span><button class="connection-action" data-connection="${i}" aria-label="查看${item.name}的状态说明">查看说明 <span aria-hidden="true">↗</span></button></li>`).join('')}</ul></div>`;
document.getElementById('semantic-grid').addEventListener('click',event=>{const theme=event.target.closest('[data-list-theme]');if(theme){document.getElementById('connection-example').dataset.theme=theme.dataset.listTheme;document.querySelectorAll('[data-list-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b===theme)));return}const action=event.target.closest('[data-connection]');if(action){const item=connectionCases[Number(action.dataset.connection)],dialog=document.getElementById('connection-dialog');document.getElementById('connection-title').textContent=item.name+' · '+item.state;document.getElementById('connection-description').textContent=item.explain;dialog.dataset.theme=document.getElementById('connection-example').dataset.theme;dialog.showModal()}});
document.getElementById('contrast-strip').innerHTML=[['橙底深色字',T.brand.primary,T.brand.ink],['浅色辅助字',T.light.surface,T.light.muted],['深色辅助字',T.dark.surface,T.dark.muted],['浅色链接文字',T.light.surface,T.brand.textLight]].map(([label,bg,fg])=>`<span>${label}<b>${contrast(bg,fg).toFixed(2)}:1</b></span>`).join('');
document.getElementById('space-scale').innerHTML=T.space.map(v=>`<span class="space-step"><i style="--size:${v}px" aria-hidden="true"></i><span>${v}</span></span>`).join('');
const copyToast=document.getElementById('copy-toast');
let toastTimer,toastRemaining=0,toastStarted=0;
function closeCopyToast(){clearTimeout(toastTimer);copyToast.classList.remove('visible');copyToast.hidden=true;}
function resumeCopyToast(){clearTimeout(toastTimer);toastStarted=Date.now();toastTimer=setTimeout(closeCopyToast,toastRemaining);}
function pauseCopyToast(){clearTimeout(toastTimer);toastRemaining=Math.max(0,toastRemaining-(Date.now()-toastStarted));}
function showCopyToast(message){clearTimeout(toastTimer);document.getElementById('copy-toast-message').textContent=message;copyToast.hidden=false;copyToast.classList.add('visible');toastRemaining=T.feedback.toastMs;resumeCopyToast();}
copyToast.querySelector('button').addEventListener('click',closeCopyToast);
copyToast.addEventListener('mouseenter',pauseCopyToast);copyToast.addEventListener('focusin',pauseCopyToast);
copyToast.addEventListener('mouseleave',()=>{if(!copyToast.contains(document.activeElement))resumeCopyToast()});
copyToast.addEventListener('focusout',()=>{if(!copyToast.matches(':hover'))resumeCopyToast()});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-copy]');if(!button)return;const value=button.dataset.copy;try{await navigator.clipboard.writeText(value);showCopyToast('已复制 '+value)}catch{showCopyToast('色值：'+value)}});
function setViewport(width){
 const L=T.layout,mobile=width<=L.mobileMax,tablet=width<=L.tabletMax&&!mobile,sidebar=mobile?0:tablet?L.compactSidebar:L.sidebar,gutter=mobile?L.mobileGutter:tablet?L.tabletGutter:L.desktopGutter,cols=mobile?L.mobileColumns:tablet?L.tabletColumns:L.desktopColumns,main=Math.min(width-sidebar-2*gutter,L.workspaceMax),outer=(width-sidebar-main)/2;
 document.querySelectorAll('[data-width]').forEach(b=>{const active=Number(b.dataset.width)===width;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active))});
 const f=document.getElementById('layout-facts');f.innerHTML=[['内容宽度',`${main}px`],['侧栏宽度',`${sidebar}px`],['工作区左右留白',`${outer}px`],['栅格 / 栏距',`${cols} / ${mobile?T.layout.mobileGap:T.layout.desktopGap}px`]].map(([n,v])=>`<div><span>${n}</span><b>${v}</b></div>`).join('');
 const W=1000,H=360,scale=mobile?310/width:960/width,frameW=width*scale,left=(W-frameW)/2,side=sidebar*scale,contentX=left+side+outer*scale,contentW=main*scale,pad=mobile?8:12,split=!mobile&&main>=T.layout.overviewSplitMin;
 const gridGap=(mobile?T.layout.mobileGap:T.layout.desktopGap)*scale,colWidth=(contentW-gridGap*(cols-1))/cols;let grid='';for(let i=0;i<cols;i++){const x=contentX+i*(colWidth+gridGap);grid+=`<rect x="${x}" y="58" width="${colWidth}" height="268" fill="#FF8200" fill-opacity=".055"/>`}
 let panels;
 if(split){const gap=gridGap,b=T.layout.overviewAsideMin*scale,a=contentW-gap-b;panels=`<rect x="${contentX}" y="100" width="${a}" height="212" rx="7" fill="#FFFFFF" stroke="#CFCFD6"/><text x="${contentX+pad}" y="135">资产摘要</text><line x1="${contentX+pad}" y1="160" x2="${contentX+a-pad}" y2="160" stroke="#E4E4E9"/><text x="${contentX+pad}" y="188">资产趋势</text><path d="M ${contentX+pad} 280 L ${contentX+a*.25} 260 L ${contentX+a*.5} 266 L ${contentX+a*.7} 238 L ${contentX+a-pad} 220" fill="none" stroke="#131316" stroke-width="2"/><rect x="${contentX+a+gap}" y="100" width="${b}" height="110" rx="7" fill="#FFFFFF" stroke="#CFCFD6"/><text x="${contentX+a+gap+pad}" y="150">会员身份</text><text x="${contentX+a+gap+pad}" y="250">关联入口</text>`}
 else{panels=['资产摘要与趋势','会员身份','关联入口'].map((label,i)=>`<rect x="${contentX}" y="${100+i*70}" width="${contentW}" height="58" rx="7" fill="#FFFFFF" stroke="#CFCFD6"/><text x="${contentX+pad}" y="${134+i*70}">${label}</text>`).join('')}
 document.getElementById('layout-diagram').innerHTML=`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="grid-title"><title id="grid-title">${width}px 视口，内容宽 ${main}px，${cols} 栏；标题和内容共用左右边界。</title><rect x="${left}" y="8" width="${frameW}" height="326" rx="10" fill="#F7F7F7" stroke="#CFCFD6"/><path d="M${left} 45H${left+frameW}" stroke="#CFCFD6"/>${sidebar?`<rect x="${left+1}" y="46" width="${side}" height="287" fill="#E4E4E9"/><line x1="${left+side}" y1="46" x2="${left+side}" y2="333" stroke="#CFCFD6"/>`:''}<style>text{font:14px 'OpenX Spec Latin','Noto Sans SC','OpenX Spec TC',sans-serif;fill:#34343B}</style><text x="${left+16}" y="33">OpenX</text>${grid}<text x="${contentX}" y="82" font-weight="600">页面标题</text>${panels}<line x1="${contentX}" y1="57" x2="${contentX}" y2="325" stroke="#131316" stroke-dasharray="4 4"/><line x1="${contentX+contentW}" y1="57" x2="${contentX+contentW}" y2="325" stroke="#131316" stroke-dasharray="4 4"/><text x="${W/2}" y="355" text-anchor="middle">横向尺寸按比例 / 内容区域 ${main}px / 左右共同边界</text></svg>`;
}
document.getElementById('viewport-options').addEventListener('click',event=>{const b=event.target.closest('[data-width]');if(b)setViewport(Number(b.dataset.width))});setViewport(1440);
document.getElementById('component-theme').addEventListener('click',event=>{const board=document.getElementById('component-board'),dark=board.dataset.theme!=='dark';board.dataset.theme=dark?'dark':'light';document.getElementById('sample-dialog').dataset.theme=board.dataset.theme;event.currentTarget.textContent=dark?'切换为浅色':'切换为深色';event.currentTarget.setAttribute('aria-pressed',String(dark))});
document.getElementById('save-demo').addEventListener('click',event=>{const b=event.currentTarget;if(b.getAttribute('aria-busy')==='true')return;const width=b.getBoundingClientRect().width;b.style.minWidth=`${width}px`;b.setAttribute('aria-busy','true');b.innerHTML='<i class="spinner" aria-hidden="true"></i>保存中';document.getElementById('save-feedback').textContent='正在保存设置…';setTimeout(()=>{b.removeAttribute('aria-busy');b.textContent='保存设置';document.getElementById('save-feedback').textContent='设置已保存'},900)});
function selectTab(button){document.querySelectorAll('[data-tab]').forEach(b=>{const active=b===button;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});const panel=document.getElementById('sample-tab-panel');panel.setAttribute('aria-labelledby',button.id);panel.textContent=button.dataset.tab==='overview'?'当前项使用清晰的文字与底线，切换不改变容器宽度。':'记录视图保留相同的内边距、内容边界和操作位置。'}
document.querySelectorAll('[data-tab]').forEach(b=>{b.addEventListener('click',()=>selectTab(b));b.addEventListener('keydown',event=>{const tabs=[...document.querySelectorAll('[data-tab]')],index=tabs.indexOf(b);let next;if(event.key==='ArrowRight')next=tabs[(index+1)%tabs.length];if(event.key==='ArrowLeft')next=tabs[(index-1+tabs.length)%tabs.length];if(event.key==='Home')next=tabs[0];if(event.key==='End')next=tabs.at(-1);if(next){event.preventDefault();selectTab(next);next.focus()}})});
document.getElementById('open-dialog').addEventListener('click',()=>document.getElementById('sample-dialog').showModal());
document.getElementById('print-spec').addEventListener('click',()=>window.print());
