import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const T=JSON.parse(fs.readFileSync(path.join(root,'tokens.json'),'utf8'));
const kebab=s=>s.replace(/[A-Z]/g,v=>'-'+v.toLowerCase());
const declaration=(name,value)=>`  --ox-${name}: ${value};`;
const rows=[];
for(const [key,value] of Object.entries(T.brand)) rows.push(declaration(`brand-${kebab(key)}`,value));
for(const [key,value] of Object.entries(T.neutral).sort(([a],[b])=>Number(a)-Number(b))) rows.push(declaration(`neutral-${key}`,value));
for(const value of T.space) rows.push(declaration(`space-${value}`,`${value}px`));
for(const [key,value] of Object.entries(T.radius)) rows.push(declaration(`radius-${kebab(key)}`,`${value}px`));
for(const [key,value] of Object.entries(T.layout)) rows.push(declaration(`layout-${kebab(key)}`,`${value}${key.endsWith('Columns')?'':'px'}`));
for(const [key,value] of Object.entries(T.type)) {
  if(Array.isArray(value)) ['size','line-height','weight'].forEach((name,i)=>rows.push(declaration(`type-${kebab(key)}-${name}`,`${value[i]}${i<2?'px':''}`)));
}
const unit=(key,value)=>typeof value==='string'?value: /Ms$/.test(key)?`${value}ms`:/Scale$|Brightness$|^weight$|^opacity$/i.test(key)?value:`${value}px`;
function componentVariables(object,prefix='component') {
  for(const [key,value] of Object.entries(object)) {
    const name=`${prefix}-${kebab(key)}`;
    if(value && typeof value==='object' && !Array.isArray(value)) componentVariables(value,name);
    else if(typeof value==='number' || /^#[a-f\d]{3,8}$/i.test(value) || /ease$/i.test(key)) rows.push(declaration(name,unit(key,value)));
  }
}
componentVariables(T.component);
for(const [key,value] of Object.entries(T.motion)) rows.push(declaration(`motion-${kebab(key).replace(/-ms$/,'')}`,typeof value==='number'?`${value}${key.endsWith('Ms')?'ms':'px'}`:value));
for(const [key,value] of Object.entries(T.layers)) rows.push(declaration(`layer-${kebab(key)}`,value));
for(const [key,value] of Object.entries(T.elevation)) rows.push(declaration(`elevation-${kebab(key)}`,value));
for(const [key,value] of Object.entries(T.overlay||{})) rows.push(declaration(`overlay-${kebab(key)}`,typeof value==='number'?`${value}px`:value));
rows.push(declaration('font',"'OpenX Spec Latin', 'Noto Sans SC', 'OpenX Spec TC', sans-serif"));
const aliases={
 'content-workspace':'layout-workspace-max','content-marketing':'layout-marketing-max','content-settings':'layout-settings-max',sidebar:'layout-sidebar',
 'control-height':'component-button-height','radius-marketingButton':'radius-marketing-button'
};
for(const [alias,target] of Object.entries(aliases)) rows.push(declaration(alias,`var(--ox-${target})`));
for(const [key,value] of Object.entries(T.images.ratios)) rows.push(declaration(`ratio-${key.replace(':','-')}`,value.css));
const theme=name=>Object.entries(T[name]).map(([key,value])=>declaration(kebab(key),value)).join('\n');
fs.writeFileSync(path.join(root,'tokens.css'),`/* Generated by build-tokens.mjs from tokens.json — do not edit */\n:root {\n${rows.join('\n')}\n}\n:root,[data-theme="light"]{\n${theme('light')}\n}\n[data-theme="dark"]{\n${theme('dark')}\n}\n@media(prefers-reduced-motion:reduce){:root{--ox-motion-feedback:0ms;--ox-motion-overlay:0ms;--ox-component-marketing-button-arrow-ms:0ms;--ox-component-marketing-button-pressed-ms:0ms;--ox-component-marketing-button-color-ms:0ms;--ox-component-workspace-button-feedback-ms:0ms}}\n`);
fs.writeFileSync(path.join(root,'tokens.js'),`window.OPENX_TOKENS = ${JSON.stringify(T)};\n`);
fs.writeFileSync(path.join(root,'breakpoints.json'),JSON.stringify({mobile:{max:T.layout.mobileMax},tablet:{min:T.layout.mobileMax+1,max:T.layout.tabletMax},desktop:{min:T.layout.tabletMax+1},note:'CSS custom properties cannot be substituted into media queries. Compile boundaries from this source at build time.'},null,2));
fs.writeFileSync(path.join(root,'responsive.css'),`/* Generated from tokens.json. Media boundaries are build-time literals. */
.ox-container{width:100%;max-width:var(--ox-content-workspace);margin-inline:auto;padding-inline:var(--ox-layout-desktop-gutter)}
.ox-settings-container{width:100%;max-width:var(--ox-content-settings);margin-inline:auto}
.ox-grid{display:grid;grid-template-columns:repeat(${T.layout.desktopColumns},minmax(0,1fr));gap:var(--ox-layout-desktop-gap)}
.ox-mobile-only{display:none}
@media(min-width:${T.layout.mobileMax+1}px) and (max-width:${T.layout.tabletMax}px){.ox-container{padding-inline:var(--ox-layout-tablet-gutter)}.ox-grid{grid-template-columns:repeat(${T.layout.tabletColumns},minmax(0,1fr))}}
@media(max-width:${T.layout.mobileMax}px){.ox-container{padding-inline:var(--ox-layout-mobile-gutter)}.ox-grid{grid-template-columns:repeat(${T.layout.mobileColumns},minmax(0,1fr));gap:var(--ox-layout-mobile-gap)}.ox-mobile-only{display:initial}.ox-desktop-only{display:none}}
`);
console.log(`Generated ${rows.length} foundation variables, themes, runtime tokens and responsive boundaries`);
