/* Calendar enhancement keeps native date values and existing form contracts. */
(() => {
  'use strict';
  if (window.OpenXCalendar) return;
  const records = new Map(), inputRecords = new Map();
  const reducedQuery = matchMedia('(prefers-reduced-motion: reduce)');
  // The spec is Simplified Chinese; account templates keep Traditional Chinese.
  const simplifiedCopy = [['選擇','选择'],['開始','开始'],['結束','结束'],['範圍','范围'],['可選','可选'],['已選','已选'],['設定','设置'],['套用','应用'],['重設','重置'],['早於','早于'],['一個月','一个月'],['後','后']];
  function localize(text){return /^zh-(?:cn|sg|hans)(?:-|$)/i.test(document.documentElement.lang)?simplifiedCopy.reduce((copy,[from,to])=>copy.replaceAll(from,to),text):text;}
  const metrics = ['fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','color','backgroundColor','borderTopWidth','borderRightWidth','borderBottomWidth','borderLeftWidth','borderTopStyle','borderRightStyle','borderBottomStyle','borderLeftStyle','borderTopColor','borderRightColor','borderBottomColor','borderLeftColor','borderTopLeftRadius','borderTopRightRadius','borderBottomRightRadius','borderBottomLeftRadius','paddingTop','paddingBottom','paddingLeft','boxShadow'];
  const themeKeys = ['--ox-font','--ox-surface','--ox-raised','--ox-hover','--ox-selected','--ox-border','--ox-border-strong','--ox-border-hover','--ox-text','--ox-body','--ox-muted','--ox-disabled','--ox-focus','--ox-danger','--ox-danger-border','--ox-brand-primary','--ox-brand-ink','--ox-elevation-menu','--ox-layer-dropdown'];
  const nativeValue = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');
  const icon = name => `<svg viewBox="0 0 20 20" aria-hidden="true">${({calendar:'<rect x="3" y="4.5" width="14" height="12.5" rx="2"/><path d="M6.5 3v3M13.5 3v3M3 8.5h14M6.5 12h2M11.5 12h2"/>',left:'<path d="m12 5-5 5 5 5"/>',right:'<path d="m8 5 5 5-5 5"/>',down:'<path d="m6 8 4 4 4-4"/>',close:'<path d="m6 6 8 8M14 6l-8 8"/>'})[name]}</svg>`;
  let sequence = 0, active = null, scheduled = 0, needsScan = false, forcedReduction = false;
  const reduced = () => reducedQuery.matches || forcedReduction || document.documentElement.dataset.motion === 'reduce';
  const unavailable = input => input.matches(':disabled') || input.readOnly;
  const pad = n => String(n).padStart(2,'0');
  function date(y,m,d=1){const value=new Date(0);value.setHours(12,0,0,0);value.setFullYear(y,m,d);return value;}
  const iso = d => `${String(d.getFullYear()).padStart(4,'0')}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  function parse(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;const [y,m,d]=value.split('-').map(Number), result=date(y,m-1,d);return y>=1&&y<=9999&&iso(result)===value?result:null;}
  const today = () => {const d=new Date();return date(d.getFullYear(),d.getMonth(),d.getDate());};
  const addDays = (d,n) => date(d.getFullYear(),d.getMonth(),d.getDate()+n);
  const startMonth = d => date(d.getFullYear(),d.getMonth());
  const addMonths = (d,n) => date(d.getFullYear(),d.getMonth()+n);
  const format = value => value ? value.replaceAll('-','.') : localize('選擇日期');
  const monthLabel = d => `${d.getFullYear()} 年 ${d.getMonth()+1} 月`;
  const owned = target => target instanceof Element && !!target.closest('.ox-calendar,.ox-calendar-trigger');
  function label(input){if(input.getAttribute('aria-label'))return input.getAttribute('aria-label');const original=input.labels?.[0];if(original){const copy=original.cloneNode(true);copy.querySelectorAll('input,button,small,.ox-calendar').forEach(n=>n.remove());return copy.textContent.trim()||'選擇日期';}return input.title||'選擇日期';}
  function bounds(input){return [parse(input.min)?input.min:'0001-01-01',parse(input.max)?input.max:'9999-12-31'];}
  function enabled(r,value,index=r.target){const input=r.inputs[index];if(!input||unavailable(input)||!parse(value))return false;const [min,max]=bounds(input);return value>=min&&value<=max;}
  function clamp(r,d,index=r.target){const [min,max]=bounds(r.inputs[index]);const value=iso(d);return parse(value<min?min:value>max?max:value)||d;}
  function schedule(scan=false){needsScan ||= scan;if(scheduled)return;scheduled=requestAnimationFrame(()=>{scheduled=0;if(needsScan){needsScan=false;refresh();}for(const r of records.values())sync(r);if(active)position(active);});}
  function theme(r){const source=r.controls[r.target]?.input||r.inputs[0], styles=getComputedStyle(source);for(const key of themeKeys)r.panel.style.setProperty(key,styles.getPropertyValue(key));r.panel.dataset.reduced=String(reduced());r.panel.style.fontFamily=styles.fontFamily;}
  function sync(r){r.controls.forEach(c=>{const style=getComputedStyle(c.input);for(const key of metrics)c.button.style[key]=style[key];for(const key of themeKeys)c.button.style.setProperty(key,style.getPropertyValue(key));c.button.dataset.reduced=String(reduced());c.button.disabled=unavailable(c.input);c.button.hidden=!c.input.getClientRects().length||style.visibility==='hidden';c.value.textContent=r.monthOnly&&c.input.value?c.input.value.slice(0,7).replace('-','.') : format(c.input.value);c.button.dataset.empty=String(!c.input.value);c.button.dataset.invalid=String(c.input.getAttribute('aria-invalid')==='true'||c.input.classList.contains('field-error'));c.button.setAttribute('aria-label',localize(`${label(c.input)}，${c.value.textContent}`));for(const name of ['aria-describedby','aria-invalid']){const val=c.input.getAttribute(name);val===null?c.button.removeAttribute(name):c.button.setAttribute(name,val);}if(c.input.required)c.button.setAttribute('aria-required','true');else c.button.removeAttribute('aria-required');c.wrapper.style.flex=style.flex;c.wrapper.style.gridColumn=style.gridColumn;c.wrapper.style.gridRow=style.gridRow;c.wrapper.style.order=style.order;c.wrapper.style.alignSelf=style.alignSelf;});theme(r);}
  function announce(r,message){const region=r.panel.querySelector('[data-calendar-announcement]');if(region)region.textContent=localize(message);}
  function rangeError(r){if(!r.range)return '';if(r.draft[0]&&r.draft[1]&&r.draft[1]<r.draft[0])return '結束日期不能早於開始日期';for(let i=0;i<r.inputs.length;i++)if(r.draft[i]&&!enabled(r,r.draft[i],i)&&r.draft[i]!==r.inputs[i].value)return '日期超出可選範圍';return '';}
  function render(r,focusSelector){
    const focusWasInside=r.panel.contains(document.activeElement), previous=document.activeElement?.dataset?.date;
    const y=r.view.getFullYear(), m=r.view.getMonth(), error=rangeError(r);
    const narrow=r.narrow, mode=r.mode, count=r.range&&!narrow&&mode==='days'?2:1;
    let headerTitle=mode==='years'?`<span class="ox-calendar-title">${r.yearStart} – ${Math.min(9999,r.yearStart+11)}</span>`:`<button type="button" class="ox-calendar-title" data-action="years" aria-label="選擇年份，${y} 年">${y} 年${icon('down')}</button>${mode==='days'?`<button type="button" class="ox-calendar-title" data-action="months" aria-label="選擇月份，${m+1} 月">${m+1} 月${icon('down')}</button>`:''}`;
    const rangeFields=r.range?`<div class="ox-calendar-range-fields">${r.draft.map((value,i)=>`<div class="ox-calendar-endpoint" data-active="${r.target===i}"><button type="button" class="ox-calendar-endpoint-main" data-endpoint="${i}" ${unavailable(r.inputs[i])?'disabled':''}><small>${i===0?'開始日期':'結束日期'}</small><span>${value?format(value):'不限'}</span></button><button type="button" class="ox-calendar-clear-end" data-clear-end="${i}" aria-label="清除${i===0?'開始':'結束'}日期" ${!value||unavailable(r.inputs[i])?'disabled':''}>${icon('close')}</button></div>`).join('')}</div><div class="ox-calendar-shortcuts" aria-label="常用日期範圍"><button type="button" class="ox-calendar-shortcut" data-preset="7" ${r.inputs.some(unavailable)?'disabled':''}>近 7 天</button><button type="button" class="ox-calendar-shortcut" data-preset="30" ${r.inputs.some(unavailable)?'disabled':''}>近 30 天</button><button type="button" class="ox-calendar-shortcut" data-preset="month" ${r.inputs.some(unavailable)?'disabled':''}>本月</button></div>`:'';
    let body='';
    if(mode==='days'){
      const months=[];for(let i=0;i<count;i++)months.push(addMonths(r.view,i));
      const available=[];for(const month of months){const total=date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let d=1;d<=total;d++){const value=iso(date(month.getFullYear(),month.getMonth(),d));if(enabled(r,value))available.push(value);}}
      if(!available.includes(r.focusDate))r.focusDate=available.find(v=>v===r.draft[r.target])||available[0]||'';
      body=`<div class="ox-calendar-months">${months.map(month=>renderMonth(r,month)).join('')}</div>`;
    } else {
      const choices=mode==='years'?Array.from({length:12},(_,i)=>r.yearStart+i).filter(v=>v<=9999):Array.from({length:12},(_,i)=>i);
      const selected=mode==='years'?y:m;
      const permitted=choices.filter(v=>choiceEnabled(r,v));if(!permitted.includes(r.choiceFocus))r.choiceFocus=permitted.includes(selected)?selected:permitted[0];
      body=`<div class="ox-calendar-grid" role="grid" aria-label="${mode==='years'?'年份':'月份'}">${choices.map((value,i)=>`${i%3===0?'<div class="ox-calendar-row" role="row">':''}<button type="button" class="ox-calendar-choice" role="gridcell" data-choice="${value}" tabindex="${r.choiceFocus===value?0:-1}" aria-selected="${value===selected}" ${choiceEnabled(r,value)?'':'disabled'}>${mode==='years'?value+' 年':value+1+' 月'}</button>${i%3===2||i===choices.length-1?'</div>':''}`).join('')}</div>`;
    }
    const note=error||`${r.target===0?'選擇開始日期':'選擇結束日期'}，可只設定一端`;
    const footer=r.range?`<p class="ox-calendar-footer-note${error?' is-error':''}" role="status">${note}</p><div class="ox-calendar-footer-actions"><button type="button" class="ox-calendar-action" data-action="cancel">${r.inline?'重設':'取消'}</button><button type="button" class="ox-calendar-action" data-action="apply" ${error?'disabled':''}>套用</button></div>`:`<button type="button" class="ox-calendar-action" data-action="clear" ${unavailable(r.inputs[0])?'disabled':''}>清除</button><button type="button" class="ox-calendar-action" data-action="today" ${enabled(r,iso(r.monthOnly?startMonth(today()):today()))?'':'disabled'}>${r.monthOnly?'本月':'今天'}</button>`;
    r.panel.innerHTML=localize(`${rangeFields}<div class="ox-calendar-head"><div class="ox-calendar-heading" aria-live="polite">${headerTitle}</div><div class="ox-calendar-navs"><button type="button" class="ox-calendar-nav" data-action="previous" aria-label="${mode==='days'?'上一個月':mode==='years'?'前 12 年':'上一年'}" ${canNavigate(r,-1)?'':'disabled'}>${icon('left')}</button><button type="button" class="ox-calendar-nav" data-action="next" aria-label="${mode==='days'?'下一個月':mode==='years'?'後 12 年':'下一年'}" ${canNavigate(r,1)?'':'disabled'}>${icon('right')}</button></div></div>${body}<div class="ox-calendar-footer">${footer}</div><span class="ox-calendar-sr" aria-live="polite" data-calendar-announcement></span>`);
    if(focusSelector||focusWasInside){const target=r.panel.querySelector(focusSelector|| (previous?`[data-date="${previous}"]`:'[tabindex="0"]'))||r.panel.querySelector('[tabindex="0"]')||r.panel.querySelector('button:not(:disabled)');target?.focus({preventScroll:true});}
    if(!r.inline&&active===r)position(r);
  }
  function renderMonth(r,month){
    const year=month.getFullYear(), index=month.getMonth(), firstDay=month.getDay(), total=date(year,index+1,0).getDate(), now=iso(today());
    const cells=Array.from({length:42},(_,cell)=>{const day=cell-firstDay+1, value=iso(date(year,index,day));if(day<1||day>total)return `<div class="ox-calendar-cell" role="gridcell" aria-disabled="true"><span class="ox-calendar-blank" aria-hidden="true">${date(year,index,day).getDate()}</span></div>`;
      const endpoint=r.draft.includes(value), within=r.range&&r.draft[0]&&r.draft[1]&&value>=r.draft[0]&&value<=r.draft[1], name=`${year} 年 ${index+1} 月 ${day} 日${r.range&&endpoint?(value===r.draft[0]?'，開始日期':'，結束日期'):''}`;
      return `<div class="ox-calendar-cell" role="presentation" data-within="${!!within}" data-first="${value===r.draft[0]}" data-last="${value===r.draft[1]}"><button type="button" class="ox-calendar-day" role="gridcell" data-date="${value}" tabindex="${r.focusDate===value?0:-1}" aria-label="${name}" aria-selected="${endpoint}" ${value===now?'aria-current="date"':''} ${enabled(r,value)?'':'disabled'}>${day}</button></div>`;
    }).map((cell,i)=>`${i%7===0?'<div class="ox-calendar-row" role="row">':''}${cell}${i%7===6?'</div>':''}`).join('');
    return `<div class="ox-calendar-month"><div class="ox-calendar-month-label">${monthLabel(month)}</div><div class="ox-calendar-weekdays" aria-hidden="true">${['日','一','二','三','四','五','六'].map(day=>`<span>${day}</span>`).join('')}</div><div class="ox-calendar-days" role="grid" aria-label="${monthLabel(month)}">${cells}</div></div>`;
  }
  function choiceEnabled(r,value){const [min,max]=bounds(r.inputs[r.target]);if(unavailable(r.inputs[r.target]))return false;if(r.mode==='years')return value>=Number(min.slice(0,4))&&value<=Number(max.slice(0,4));const start=iso(date(r.view.getFullYear(),value)), end=iso(date(r.view.getFullYear(),value+1,0));return r.monthOnly?enabled(r,start):end>=min&&start<=max;}
  function canNavigate(r,direction){const [min,max]=bounds(r.inputs[r.target]);let start,end;if(r.mode==='years'){const year=r.yearStart+direction*12;start=`${String(Math.max(1,year)).padStart(4,'0')}-01-01`;end=`${String(Math.min(9999,year+11)).padStart(4,'0')}-12-31`;if(year<1||year>9999)return false;}else if(r.mode==='months'){const year=r.view.getFullYear()+direction;if(year<1||year>9999)return false;start=iso(date(year,0));end=iso(date(year,11,31));}else{const d=addMonths(r.view,direction);if(d.getFullYear()<1||d.getFullYear()>9999)return false;start=iso(d);end=iso(date(d.getFullYear(),d.getMonth()+1,0));}return end>=min&&start<=max;}
  function navigate(r,direction){if(!canNavigate(r,direction))return;if(r.mode==='years')r.yearStart+=direction*12;else r.view=r.mode==='months'?date(r.view.getFullYear()+direction,r.view.getMonth()):addMonths(r.view,direction);render(r,`[data-action="${direction<0?'previous':'next'}"]`);}
  function setDraft(r,value){if(!enabled(r,value))return;r.draft[r.target]=value;r.focusDate=value;if(!r.range){commit(r);return;}if(r.target===0&&!unavailable(r.inputs[1]))r.target=1;render(r,`[data-date="${value}"]`);announce(r,`${format(value)} 已選，${r.target===0?'可選擇開始日期':'可選擇結束日期'}`);}
  function commit(r){if(rangeError(r))return;const changed=[];r.inputs.forEach((input,i)=>{if(unavailable(input))return;if(input.value!==r.draft[i]){input.value=r.draft[i];changed.push(input);}});sync(r);if(!r.inline)close(r,true);else render(r);for(const input of changed){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}if(r.inline)announce(r,'日期已更新');}
  function resetDraft(r){r.draft=r.inputs.map(input=>input.value);r.focusDate=r.draft[r.target]||iso(clamp(r,today()));r.view=startMonth(parse(r.focusDate)||today());r.mode=r.monthOnly?'months':'days';r.yearStart=Math.max(1,Math.floor((r.view.getFullYear()-1)/12)*12+1);}
  function click(r,event){const button=event.target.closest('button');if(!button||button.disabled)return;const data=button.dataset;if(data.date){setDraft(r,data.date);return;}if(data.choice!==undefined){const value=Number(data.choice);if(!choiceEnabled(r,value))return;if(r.mode==='years'){r.view=date(value,r.view.getMonth());r.mode='months';r.choiceFocus=r.view.getMonth();render(r,'[tabindex="0"]');}else if(r.monthOnly){setDraft(r,iso(date(r.view.getFullYear(),value)));}else{r.view=date(r.view.getFullYear(),value);r.mode='days';r.focusDate=iso(clamp(r,r.view));render(r,'[tabindex="0"]');}return;}
    if(data.endpoint!==undefined){r.target=Number(data.endpoint);const selected=parse(r.draft[r.target]);if(selected)r.view=startMonth(selected);r.focusDate=r.draft[r.target]||iso(clamp(r,today()));r.mode='days';render(r,'[tabindex="0"]');return;}
    if(data.clearEnd!==undefined){r.draft[Number(data.clearEnd)]='';r.target=Number(data.clearEnd);render(r,`[data-endpoint="${r.target}"]`);return;}
    if(data.preset){if(r.inputs.some(unavailable))return;const end=today(),start=data.preset==='month'?startMonth(end):addDays(end,1-Number(data.preset));r.draft=[iso(clamp(r,start,0)),iso(clamp(r,end,1))];r.view=startMonth(parse(r.draft[0]));r.mode='days';r.focusDate=r.draft[0];render(r,`[data-preset="${data.preset}"]`);return;}
    switch(data.action){case 'previous':navigate(r,-1);break;case 'next':navigate(r,1);break;case 'years':r.mode='years';r.yearStart=Math.max(1,Math.floor((r.view.getFullYear()-1)/12)*12+1);r.choiceFocus=r.view.getFullYear();render(r,'[tabindex="0"]');break;case 'months':r.mode='months';r.choiceFocus=r.view.getMonth();render(r,'[tabindex="0"]');break;case 'apply':commit(r);break;case 'cancel':if(r.inline){resetDraft(r);render(r,'[tabindex="0"]');}else close(r,true);break;case 'clear':r.draft=[''];commit(r);break;case 'today':setDraft(r,iso(r.monthOnly?startMonth(today()):today()));break;}
  }
  function keydown(r,event){if(event.key==='Escape'){if(!r.inline){event.preventDefault();event.stopPropagation();close(r,true);}return;}if(event.key==='Tab'&&!r.inline){const buttons=[...r.panel.querySelectorAll('button:not(:disabled)')].filter(el=>el.tabIndex>=0);const first=buttons[0],last=buttons.at(-1);if((event.shiftKey&&document.activeElement===first)||(!event.shiftKey&&document.activeElement===last)){event.preventDefault();close(r,true);if(!event.shiftKey){const focusable=[...document.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),[tabindex="0"]')].filter(el=>el.tabIndex>=0&&el.getClientRects().length&&!r.panel.contains(el));const index=focusable.indexOf(r.controls[r.openedFrom].button);focusable[index+1]?.focus();}}return;}
    const button=event.target.closest('button'), key=event.key;if(!button||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(key))return;
    if(button.dataset.date){event.preventDefault();const current=parse(button.dataset.date);let next;if(key==='Home')next=addDays(current,-current.getDay());else if(key==='End')next=addDays(current,6-current.getDay());else if(key==='PageUp'||key==='PageDown'){const step=(key==='PageUp'?-1:1)*(event.shiftKey?12:1),month=addMonths(startMonth(current),step);next=date(month.getFullYear(),month.getMonth(),Math.min(current.getDate(),date(month.getFullYear(),month.getMonth()+1,0).getDate()));}else next=addDays(current,({ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7})[key]);next=clamp(r,next);const value=iso(next);if(!enabled(r,value))return;r.focusDate=value;const finalMonth=addMonths(r.view,r.range&&!r.narrow?1:0);if(next<r.view||startMonth(next)>finalMonth)r.view=startMonth(next);render(r,`[data-date="${value}"]`);
    }else if(button.dataset.choice!==undefined){event.preventDefault();let next=Number(button.dataset.choice);const start=r.mode==='years'?r.yearStart:0,end=start+11;if(key==='Home')next=start;else if(key==='End')next=end;else if(key==='PageUp'||key==='PageDown'){navigate(r,key==='PageUp'?-1:1);r.panel.querySelector('[tabindex="0"]')?.focus();return;}else next+=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3})[key];next=Math.max(start,Math.min(end,next));if(!choiceEnabled(r,next))return;r.choiceFocus=next;render(r,`[data-choice="${next}"]`);}
  }
  function position(r){if(r.inline||active!==r)return;const anchor=r.controls[r.openedFrom].button.getBoundingClientRect(),vv=visualViewport,gutter=12,width=vv?.width||innerWidth,height=vv?.height||innerHeight,x=vv?.offsetLeft||0,y=vv?.offsetTop||0;const narrow=width<660;if(r.narrow!==narrow){r.narrow=narrow;r.panel.dataset.narrow=String(narrow);render(r);return;}r.panel.style.width=`${Math.min(width-gutter*2,r.range&&!narrow?680:336)}px`;r.panel.style.maxHeight=`${height-gutter*2}px`;const box=r.panel.getBoundingClientRect();const left=Math.max(x+gutter,Math.min(anchor.left,x+width-gutter-box.width));const below=y+height-anchor.bottom-gutter-8,above=anchor.top-y-gutter-8;let top=anchor.bottom+8;if(below<box.height&&above>below)top=anchor.top-box.height-8;top=Math.max(y+gutter,Math.min(top,y+height-gutter-box.height));r.panel.style.left=`${left}px`;r.panel.style.top=`${top}px`;}
  function open(r,index=0){if(unavailable(r.inputs[index]))return;if(active&&active!==r)close(active,false);r.target=index;r.openedFrom=index;resetDraft(r);sync(r);if(r.inline){render(r,'[tabindex="0"]');return;}clearTimeout(r.closeTimer);active=r;r.panel.hidden=false;r.panel.dataset.state='opening';if(r.panel.showPopover&&!r.panel.matches(':popover-open'))r.panel.showPopover();r.controls.forEach(c=>c.button.setAttribute('aria-expanded','true'));render(r);position(r);r.panel.querySelector('[tabindex="0"]')?.focus({preventScroll:true});requestAnimationFrame(()=>{if(active===r)r.panel.dataset.state='open';});}
  function close(r,focus=false){if(!r||r.inline)return;if(active===r)active=null;r.controls.forEach(c=>c.button.setAttribute('aria-expanded','false'));r.panel.dataset.state='closing';clearTimeout(r.closeTimer);r.closeTimer=setTimeout(()=>{if(r.panel.hidePopover&&r.panel.matches(':popover-open'))r.panel.hidePopover();r.panel.hidden=true;},reduced()?0:120);if(focus&&r.controls[r.openedFrom]?.button.isConnected)r.controls[r.openedFrom].button.focus({preventScroll:true});}
  function control(r,input,index){const wrapper=document.createElement('span');wrapper.className='ox-calendar-wrap';const button=document.createElement('button');button.type='button';button.className='ox-calendar-trigger';button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-expanded',String(r.inline));button.setAttribute('aria-controls',r.panel.id);const value=document.createElement('span');value.className='ox-calendar-trigger__value';button.append(value);button.insertAdjacentHTML('beforeend',icon('calendar'));const c={input,wrapper,button,value,originalTab:input.getAttribute('tabindex'),originalHidden:input.getAttribute('aria-hidden'),originalValue:Object.getOwnPropertyDescriptor(input,'value')};input.before(wrapper);wrapper.append(input,button);input.classList.add('ox-calendar-native');input.tabIndex=-1;input.setAttribute('aria-hidden','true');inputRecords.set(input,r);if(!c.originalValue&&nativeValue){Object.defineProperty(input,'value',{configurable:true,enumerable:nativeValue.enumerable,get(){return nativeValue.get.call(this)},set(value){nativeValue.set.call(this,value);schedule();}});}
    c.onInput=()=>{schedule();if(r.inline){r.draft=r.inputs.map(i=>i.value);render(r);}};c.onFocus=()=>button.focus({preventScroll:true});c.onClick=event=>{event.preventDefault();open(r,index);};c.onInvalid=event=>{event.preventDefault();button.setAttribute('aria-invalid','true');button.focus();};input.addEventListener('input',c.onInput);input.addEventListener('change',c.onInput);input.addEventListener('focus',c.onFocus);input.addEventListener('click',c.onClick);input.addEventListener('invalid',c.onInvalid);button.addEventListener('click',()=>{active===r&&r.openedFrom===index?close(r,true):open(r,index)});button.addEventListener('keydown',event=>{if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();open(r,index);}});resize.observe(input);return c;
  }
  function create(key,inputs){const inlineHost=inputs[0].closest('[data-calendar-inline]'),panel=document.createElement('div');panel.id=`ox-calendar-${++sequence}`;panel.className='ox-calendar';panel.setAttribute('role',inlineHost?'group':'dialog');panel.setAttribute('aria-label',localize(inputs.length>1?'選擇日期範圍':'選擇日期'));if(!inlineHost){panel.hidden=true;if('showPopover' in panel)panel.setAttribute('popover','manual');}panel.dataset.inline=String(!!inlineHost);panel.dataset.range=String(inputs.length>1);panel.dataset.state='open';const r={key,inputs,controls:[],panel,inline:!!inlineHost,inlineHost,range:inputs.length>1,monthOnly:inputs.length===1&&inputs[0].dataset.calendar==='month',target:0,openedFrom:0,draft:inputs.map(i=>i.value),view:startMonth(today()),mode:'days',narrow:innerWidth<660,yearStart:2021,choiceFocus:0,focusDate:'',closeTimer:0};records.set(key,r);r.controls=inputs.map((input,i)=>control(r,input,i));if(inlineHost)inlineHost.append(panel);else document.body.append(panel);panel.dataset.narrow=String(r.narrow);panel.addEventListener('click',event=>click(r,event));panel.addEventListener('keydown',event=>keydown(r,event));resetDraft(r);sync(r);if(r.inline){r.narrow=inlineHost.clientWidth<620;panel.dataset.narrow=String(r.narrow);render(r);resize.observe(inlineHost);}}
  function remove(r){close(r,false);clearTimeout(r.closeTimer);if(r.inlineHost)resize.unobserve(r.inlineHost);r.panel.remove();for(const c of r.controls){resize.unobserve(c.input);c.button.remove();if(c.wrapper.isConnected&&c.input.parentElement===c.wrapper)c.wrapper.replaceWith(c.input);else c.wrapper.remove();c.input.classList.remove('ox-calendar-native');for(const [name,value] of [['tabindex',c.originalTab],['aria-hidden',c.originalHidden]])value===null?c.input.removeAttribute(name):c.input.setAttribute(name,value);if(c.originalValue)Object.defineProperty(c.input,'value',c.originalValue);else delete c.input.value;c.input.removeEventListener('input',c.onInput);c.input.removeEventListener('change',c.onInput);c.input.removeEventListener('focus',c.onFocus);c.input.removeEventListener('click',c.onClick);c.input.removeEventListener('invalid',c.onInvalid);inputRecords.delete(c.input);}records.delete(r.key);}
  function refresh(scope=document){for(const r of records.values())if(r.inputs.some(input=>!input.isConnected||input.type!=='date'))remove(r);const found=[...(scope.matches?.('input[type=date]')?[scope]:[]),...scope.querySelectorAll('input[type=date]:not([data-calendar=native])')];for(const input of found){if(inputRecords.has(input))continue;const parent=input.closest('[data-calendar-range],.bc-date-range'),group=parent?[...parent.querySelectorAll('input[type=date]')].slice(0,2):[input],key=group.length===2?parent:input;if(records.has(key))continue;create(key,group);}for(const r of records.values())sync(r);}
  const resize=new ResizeObserver(entries=>{for(const entry of entries){const r=records.get(entry.target)||[...records.values()].find(item=>item.inlineHost===entry.target);if(r?.inline){const narrow=r.inlineHost.clientWidth<620;if(narrow!==r.narrow){r.narrow=narrow;r.panel.dataset.narrow=String(narrow);render(r);}}}schedule();});
  const observer=new MutationObserver(changes=>{if(changes.some(change=>!owned(change.target)&&!(change.type==='childList'&&[...change.addedNodes,...change.removedNodes].every(node=>owned(node))))){schedule(true);}});
  function start(){refresh();observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['data-theme','disabled','readonly','type','min','max','required','value','aria-invalid','aria-describedby','hidden']});document.addEventListener('pointerdown',event=>{if(active&&!active.panel.contains(event.target)&&!active.controls.some(c=>c.button.contains(event.target)))close(active,false);},true);document.addEventListener('keydown',event=>{if(active&&event.key==='Escape'){event.preventDefault();close(active,true);}});document.addEventListener('scroll',()=>{if(active)position(active);},true);window.addEventListener('resize',()=>schedule());visualViewport?.addEventListener('resize',()=>schedule());visualViewport?.addEventListener('scroll',()=>schedule());document.addEventListener('reset',()=>setTimeout(()=>{for(const r of records.values()){resetDraft(r);if(r.inline)render(r);}schedule();},0));document.fonts?.ready.then(()=>schedule());}
  document.addEventListener('openx:motion-preference',event=>{forcedReduction=event.detail?.reduce===true;schedule();});
  window.OpenXCalendar={refresh,close:()=>close(active,false)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
