(() => {
  'use strict';
  const root=document.querySelector('#motion-system'); if(!root)return;
  const $=s=>root.querySelector(s), $$=s=>[...root.querySelectorAll(s)];
  const os=matchMedia('(prefers-reduced-motion: reduce)');
  const reduced=()=>os.matches||document.documentElement.dataset.motion==='reduce';
  const ease='cubic-bezier(.2,.8,.2,1)';
  let toastTimer,toastRemaining=5000,toastStarted=0,loadTimer,filter='all',page=0;
  function enter(el,duration=180,distance=4){el.getAnimations().forEach(a=>a.cancel());if(!reduced())el.animate([{opacity:0,transform:`translateY(${distance}px)`},{opacity:1,transform:'translateY(0)'}],{duration,easing:ease});}
  function motionMode(){const forced=$('#mf-reduce').checked;document.documentElement.dataset.motion=forced?'reduce':'standard';document.dispatchEvent(new CustomEvent('openx:motion-preference',{detail:{reduce:reduced()}}));if(reduced())root.getAnimations({subtree:true}).forEach(a=>a.cancel());$('#mf-mode-note').textContent=os.matches?'系统已启用减少动态效果 · 内容立即显示，操作完整保留':forced?'减少动态效果 · 内容立即显示，操作完整保留':'标准动效 · 同一套规则适用于浅色与深色界面';}
  $('#mf-reduce').addEventListener('change',motionMode);os.addEventListener('change',motionMode);motionMode();
  $('#mf-theme').addEventListener('click',()=>{const theme=$('#mf-workbench').dataset.theme==='dark'?'light':'dark';$$('[data-theme]').forEach(el=>el.dataset.theme=theme);$('#mf-theme').textContent=theme==='dark'?'切换浅色':'切换深色';});
  function switchTab(tab){$$('.mf-tabs [role=tab]').forEach(el=>{const on=el===tab;el.setAttribute('aria-selected',on);el.tabIndex=on?0:-1;const panel=document.getElementById(el.getAttribute('aria-controls'));panel.hidden=!on;if(on)enter(panel);});if(tab.id!=='mf-tab-loading')cancelLoad(false);}
  const tabs=$$('.mf-tabs [role=tab]');tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>switchTab(tab));tab.addEventListener('keydown',e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();switchTab(tabs[next]);tabs[next].focus();});});
  function resumeToast(){clearTimeout(toastTimer);if($('#mf-toast').hidden||document.hidden||$('#mf-toast').matches(':hover')||$('#mf-toast').contains(document.activeElement))return;toastStarted=performance.now();toastTimer=setTimeout(hideToast,toastRemaining);}
  function pauseToast(){if(toastTimer){clearTimeout(toastTimer);toastTimer=undefined;toastRemaining=Math.max(0,toastRemaining-(performance.now()-toastStarted));}}
  function hideToast(){$('#mf-toast').hidden=true;clearTimeout(toastTimer);toastTimer=undefined;}
  function toast(message){$('#mf-toast>span').textContent=message;$('#mf-toast').hidden=false;toastRemaining=5000;resumeToast();}
  $('#mf-toast-close').addEventListener('click',hideToast);$('#mf-toast').addEventListener('pointerenter',pauseToast);$('#mf-toast').addEventListener('pointerleave',resumeToast);$('#mf-toast').addEventListener('focusin',pauseToast);$('#mf-toast').addEventListener('focusout',()=>queueMicrotask(resumeToast));document.addEventListener('visibilitychange',()=>document.hidden?pauseToast():resumeToast());
  $$('[data-mf-open]').forEach(btn=>btn.addEventListener('click',()=>document.getElementById(btn.dataset.mfOpen).showModal()));
  $$('[data-mf-close]').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));
  const form=$('#mf-preferences');form.addEventListener('input',()=>{$('#mf-save-state').textContent='有未保存的变更';});
  form.addEventListener('submit',e=>{e.preventDefault();const field=$('#mf-name'),valid=field.value.trim().length>=2;field.setAttribute('aria-invalid',String(!valid));$('#mf-name-help').textContent=valid?'2 至 16 个字符':'昵称至少需要 2 个字符';if(!valid){field.focus();enter($('#mf-name-help'),160,0);return;}$('#mf-dialog').showModal();});
  $('#mf-confirm').addEventListener('click',()=>{$('#mf-dialog').close();$('#mf-save-state').textContent='设置已同步';toast('通知偏好已保存');});
  const pop=$('#mf-popover'),more=$('#mf-more');function positionPopover(){const r=more.getBoundingClientRect(),w=208,h=104;pop.style.left=`${Math.max(8,Math.min(innerWidth-w-8,r.left))}px`;pop.style.top=`${r.bottom+h+16>innerHeight?Math.max(8,r.top-h-8):r.bottom+8}px`;}
  more.addEventListener('click',()=>{if(pop.matches(':popover-open'))pop.hidePopover();else{positionPopover();pop.showPopover();pop.querySelector('button').focus({preventScroll:true});}});pop.addEventListener('beforetoggle',e=>{if(e.newState==='closed'&&pop.contains(document.activeElement))more.focus({preventScroll:true});});pop.addEventListener('toggle',e=>more.setAttribute('aria-expanded',e.newState==='open'));pop.addEventListener('keydown',e=>{const buttons=[...pop.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length].focus();}});addEventListener('resize',()=>{if(pop.matches(':popover-open'))positionPopover();});let popFrame=0;addEventListener('scroll',()=>{if(!pop.matches(':popover-open')||popFrame)return;popFrame=requestAnimationFrame(()=>{popFrame=0;const r=more.getBoundingClientRect();if(r.bottom<=0||r.top>=innerHeight)pop.hidePopover();else positionPopover();});},true);
  $$('[data-mf-action]').forEach(btn=>btn.addEventListener('click',()=>{pop.hidePopover();if(btn.dataset.mfAction==='records')$('#mf-drawer').showModal();else{form.reset();$('#mf-name').removeAttribute('aria-invalid');$('#mf-name-help').textContent='2 至 16 个字符';$('#mf-save-state').textContent='有未保存的变更';toast('偏好已恢复默认，可保存设置');}}));
  const tip=$('.mf-tip-wrap');tip.addEventListener('keydown',e=>{if(e.key==='Escape')tip.dataset.dismissed='true';});['pointerleave','focusout'].forEach(event=>tip.addEventListener(event,()=>delete tip.dataset.dismissed));
  const rows=[['更新通知偏好','2026.10.01 14:30','settings'],['开启安全提醒','2026.10.01 10:12','security'],['更新公开昵称','2026.09.28 16:05','settings'],['确认登录设备','2026.09.27 09:24','security'],['调整汇总频率','2026.09.26 18:46','settings'],['更新安全设置','2026.09.25 12:10','security']];
  function records(){const list=rows.filter(r=>filter==='all'||r[2]===filter),pages=Math.ceil(list.length/3);page=Math.min(page,pages-1);$('#mf-records').innerHTML=list.slice(page*3,page*3+3).map(r=>`<div class="mf-record" data-motion-enter><span>${r[0]}</span><time>${r[1]}</time></div>`).join('');$('#mf-page-count').textContent=`共 ${list.length} 条 · 第 ${page+1} / ${pages} 页`;$('#mf-prev').disabled=page===0;$('#mf-next').disabled=page===pages-1;}
  $$('[data-mf-filter]').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.mfFilter;page=0;$$('[data-mf-filter]').forEach(b=>b.setAttribute('aria-pressed',b===btn));records();}));$('#mf-prev').addEventListener('click',()=>{page--;records();});$('#mf-next').addEventListener('click',()=>{page++;records();});records();
  function busy(on){$('#mf-load-region').setAttribute('aria-busy',on);$('#mf-load').disabled=on;$('#mf-load-error').disabled=on;$('#mf-cancel-load').hidden=!on;$('#mf-load').textContent=on?'正在读取':'刷新记录';}
  function cancelLoad(announce=true){if(!loadTimer)return;clearTimeout(loadTimer);loadTimer=undefined;busy(false);$('#mf-load-region').innerHTML='<div class="mf-load-result"><b>读取已取消</b><span>可随时重新刷新记录</span></div>';$('#mf-load-status').textContent=announce?'读取已取消':'';}
  function load(fail=false){cancelLoad(false);busy(true);$('#mf-load-status').textContent='正在读取记录';$('#mf-load-region').innerHTML='<div aria-hidden="true"><div class="mf-skeleton-line motion-skeleton"></div><div class="mf-skeleton-line motion-skeleton"></div><div class="mf-skeleton-line motion-skeleton"></div></div>';loadTimer=setTimeout(()=>{loadTimer=undefined;busy(false);$('#mf-load-region').innerHTML=fail?'<div class="mf-load-result error" data-motion-enter><b>暂时无法读取记录</b><span>请检查连接后重试，当前设置已保留</span><button class="ui-btn" id="mf-retry">重新读取</button></div>':'<div class="mf-load-result" data-motion-enter><b>记录已更新</b><span>通知偏好 · 安全提醒 · 公开昵称</span></div>';$('#mf-load-status').textContent=fail?'读取未完成':'已读取 3 条记录';$('#mf-retry')?.addEventListener('click',()=>load(false));},1100);}
  $('#mf-load').addEventListener('click',()=>load());$('#mf-load-error').addEventListener('click',()=>load(true));$('#mf-cancel-load').addEventListener('click',()=>cancelLoad());
  function replayMedia(){const items=[...$('#mf-reveal-region').children];items.forEach((el,i)=>{el.getAnimations().forEach(a=>a.cancel());if(!reduced())el.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:320,delay:i*40,easing:ease,fill:'backwards'});});}
  $('#mf-replay').addEventListener('click',replayMedia);
  addEventListener('pagehide',()=>{clearTimeout(loadTimer);clearTimeout(toastTimer);});
})();
