/* Progressive enhancement for the specification's single-select controls. */
(() => {
  'use strict';
  if (window.OpenXSelectMenu) return;
  const selector='.field select,select.filter-control,.bc-field select,.template-options select,.mf-field select';
  const records=new Map();
  const reduce=matchMedia('(prefers-reduced-motion: reduce)');
  const nativePrototype=HTMLSelectElement.prototype;
  const metricProperties=['fontFamily','fontSize','fontWeight','fontStyle','letterSpacing','lineHeight','color','backgroundColor','borderTopWidth','borderRightWidth','borderBottomWidth','borderLeftWidth','borderTopStyle','borderRightStyle','borderBottomStyle','borderLeftStyle','borderTopColor','borderRightColor','borderBottomColor','borderLeftColor','borderTopLeftRadius','borderTopRightRadius','borderBottomRightRadius','borderBottomLeftRadius','paddingTop','paddingBottom','paddingLeft','boxShadow','textTransform','direction'];
  const themeProperties=['--ox-font','--ox-text','--ox-muted','--ox-disabled','--ox-surface','--ox-raised','--ox-hover','--ox-border','--ox-border-hover','--ox-danger-border','--ox-focus','--ox-layer-popover'];
  let openRecord=null,frame=0,id=0,scanNeeded=false,typeBuffer='',typeAt=0,forcedReduction=document.documentElement.dataset.motion==='reduce';
  const reduced=()=>reduce.matches||forcedReduction||document.documentElement.dataset.motion==='reduce';
  const element=target=>target instanceof Element ? target : target?.parentElement;
  const owned=node=>element(node)?.closest('.ox-select-trigger,.ox-select-menu');
  function enqueue(needsScan=false){scanNeeded ||= needsScan;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(scanNeeded){scanNeeded=false;scan();}for(const r of records.values())update(r);if(openRecord)positionMenu(openRecord);});}
  function labelOf(select){const explicit=select.getAttribute('aria-label');if(explicit)return explicit;const labelled=select.getAttribute('aria-labelledby');if(labelled)return labelled.split(/\s+/).map(id=>document.getElementById(id)?.textContent||'').join(' ').trim();const label=select.labels?.[0];if(label){const copy=label.cloneNode(true);copy.querySelectorAll('select,button,input,small,svg').forEach(n=>n.remove());return copy.textContent.trim();}return select.title || '選擇選項';}
  function syncValue(r){const option=r.select.selectedOptions[0];r.value.textContent=option?.label||'';r.button.setAttribute('aria-label',`${labelOf(r.select)}${option?'，'+option.label:''}`);r.button.disabled=r.select.disabled;for(const name of ['aria-describedby','aria-invalid','aria-required']){const value=r.select.getAttribute(name);if(value!==null)r.button.setAttribute(name,value);else r.button.removeAttribute(name);}if(r.select.required)r.button.setAttribute('aria-required','true');if(r===openRecord){r.options.forEach((el,i)=>el.setAttribute('aria-selected',String(i===r.select.selectedIndex)));}}
  function update(r){if(!r.select.isConnected)return;const source=r.select.getBoundingClientRect();const style=getComputedStyle(r.select);const visible=r.select.getClientRects().length>0&&style.visibility!=='hidden';r.button.hidden=!visible;if(!visible){if(openRecord===r)close(r,false);return;}for(const key of metricProperties)r.button.style[key]=style[key];for(const key of themeProperties){const value=style.getPropertyValue(key);r.button.style.setProperty(key,value);r.menu.style.setProperty(key,value);}r.wrapper.style.flex=style.flex;r.wrapper.style.alignSelf=style.alignSelf;r.wrapper.style.order=style.order;r.wrapper.style.gridColumn=style.gridColumn;r.wrapper.style.gridRow=style.gridRow;if(openRecord===r&&(source.bottom<=0||source.top>=innerHeight||source.right<=0||source.left>=innerWidth))close(r,false);r.menu.style.fontFamily=style.fontFamily;r.menu.style.fontSize=style.fontSize;r.menu.style.fontWeight=style.fontWeight;syncValue(r);}
  function optionsOf(r){return [...r.select.options];}
  function enabled(r,index){const option=r.select.options[index];return !!option&&!option.disabled&&!option.closest('optgroup')?.disabled&&!option.hidden;}
  function firstEnabled(r,last=false){const options=optionsOf(r);return last?options.findLastIndex((_,i)=>enabled(r,i)):options.findIndex((_,i)=>enabled(r,i));}
  function setActive(r,index,scroll=true){if(index<0)return;r.active=index;r.options.forEach((el,i)=>el.classList.toggle('is-active',i===index));r.button.setAttribute('aria-activedescendant',r.options[index]?.id||'');if(scroll)r.options[index]?.scrollIntoView({block:'nearest',inline:'nearest'});}
  function populate(r){r.menu.replaceChildren();r.options=[];let group=null;optionsOf(r).forEach((option,index)=>{const parent=option.parentElement;if(parent instanceof HTMLOptGroupElement&&group!==parent){group=parent;const title=document.createElement('div');title.className='ox-select-group';title.setAttribute('role','presentation');title.textContent=parent.label;r.menu.append(title);}const row=document.createElement('div');row.className='ox-select-option';row.id=`${r.menu.id}-option-${index}`;row.setAttribute('role','option');row.setAttribute('aria-selected',String(index===r.select.selectedIndex));if(!enabled(r,index))row.setAttribute('aria-disabled','true');row.hidden=option.hidden;const text=document.createElement('span');text.className='ox-select-option__label';text.textContent=option.label;row.append(text);row.insertAdjacentHTML('beforeend','<svg class="ox-select-option__check" viewBox="0 0 20 20" aria-hidden="true"><path d="m4 10 4 4 8-8"/></svg>');row.addEventListener('pointerdown',event=>event.preventDefault());row.addEventListener('pointermove',()=>{if(enabled(r,index))setActive(r,index,false);});row.addEventListener('click',()=>{if(enabled(r,index))choose(r,index)});r.menu.append(row);r.options.push(row);});}
  function positionMenu(r){if(r!==openRecord)return;const box=r.button.getBoundingClientRect();const vv=window.visualViewport;const leftEdge=vv?.offsetLeft||0,topEdge=vv?.offsetTop||0,viewportWidth=vv?.width||innerWidth,viewportHeight=vv?.height||innerHeight;const gutter=8,gap=6;const maxWidth=Math.max(0,viewportWidth-gutter*2);r.menu.style.width='max-content';r.menu.style.minWidth=`${Math.min(box.width,maxWidth)}px`;r.menu.style.maxWidth=`${maxWidth}px`;r.menu.style.maxHeight='none';const height=Math.min(r.menu.scrollHeight,320);const below=topEdge+viewportHeight-box.bottom-gap-gutter;const above=box.top-topEdge-gap-gutter;const aboveSide=below<height&&above>below;const available=Math.max(44,aboveSide?above:below);r.menu.style.maxHeight=`${Math.min(320,available)}px`;const measured=r.menu.getBoundingClientRect();const left=Math.max(leftEdge+gutter,Math.min(box.left,leftEdge+viewportWidth-gutter-measured.width));const top=aboveSide?Math.max(topEdge+gutter,box.top-gap-measured.height):Math.min(box.bottom+gap,topEdge+viewportHeight-gutter-measured.height);r.menu.style.left=`${left}px`;r.menu.style.top=`${Math.max(topEdge+gutter,top)}px`;r.menu.dataset.side=aboveSide?'above':'below';}
  function followPosition(r){if(openRecord!==r)return;const box=r.button.getBoundingClientRect();const key=[box.x,box.y,box.width,box.height].map(n=>Math.round(n*4)).join(':');if(key!==r.positionKey){r.positionKey=key;positionMenu(r);}r.positionFrame=requestAnimationFrame(()=>followPosition(r));}
  function open(r,initial){if(r.select.disabled||r.button.hidden)return;if(openRecord&&openRecord!==r)close(openRecord,false);clearTimeout(r.closeTimer);openRecord=r;populate(r);update(r);r.menu.hidden=false;r.menu.dataset.state='opening';r.button.setAttribute('aria-expanded','true');r.menu.setAttribute('aria-label',labelOf(r.select));positionMenu(r);setActive(r,initial??(enabled(r,r.select.selectedIndex)?r.select.selectedIndex:firstEnabled(r)));r.button.focus({preventScroll:true});cancelAnimationFrame(r.positionFrame);followPosition(r);requestAnimationFrame(()=>{if(openRecord===r)r.menu.dataset.state='open';});}
  function close(r,focus=false){if(!r)return;if(openRecord===r)openRecord=null;cancelAnimationFrame(r.positionFrame);r.button.setAttribute('aria-expanded','false');r.button.removeAttribute('aria-activedescendant');r.menu.dataset.state='closing';clearTimeout(r.closeTimer);r.closeTimer=setTimeout(()=>{r.menu.hidden=true;},reduced()?0:120);if(focus&&r.button.isConnected)r.button.focus({preventScroll:true});typeBuffer='';}
  function choose(r,index){if(!enabled(r,index))return;const changed=r.select.selectedIndex!==index;r.select.selectedIndex=index;syncValue(r);close(r,true);if(changed){r.select.dispatchEvent(new Event('input',{bubbles:true}));r.select.dispatchEvent(new Event('change',{bubbles:true}));}enqueue(true);}
  function move(r,direction){let i=r.active;for(let count=0;count<r.select.options.length;count++){i+=direction;if(i<0||i>=r.select.options.length)break;if(enabled(r,i)){setActive(r,i);break;}}}
  function keydown(r,event){const key=event.key;const isOpen=openRecord===r;if(key==='Tab'){if(isOpen)close(r,false);return;}if(key==='Escape'&&isOpen){event.preventDefault();event.stopPropagation();close(r,true);return;}if(['ArrowDown','ArrowUp','Home','End','Enter',' '].includes(key)){event.preventDefault();if(!isOpen){open(r,key==='Home'?firstEnabled(r):key==='End'?firstEnabled(r,true):undefined);return;}if(key==='ArrowDown')move(r,1);else if(key==='ArrowUp')move(r,-1);else if(key==='Home')setActive(r,firstEnabled(r));else if(key==='End')setActive(r,firstEnabled(r,true));else choose(r,r.active);return;}if(key.length===1&&!event.ctrlKey&&!event.metaKey&&!event.altKey){event.preventDefault();if(!isOpen)open(r);const now=Date.now();typeBuffer=now-typeAt>700?key:typeBuffer+key;typeAt=now;const index=optionsOf(r).findIndex((o,i)=>enabled(r,i)&&o.label.toLocaleLowerCase().startsWith(typeBuffer.toLocaleLowerCase()));if(index>=0)setActive(r,index);}}
  function enhance(select){if(records.has(select)||select.multiple||select.size>1)return;const button=document.createElement('button');button.type='button';button.className='ox-select-trigger';button.setAttribute('role','combobox');button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');const value=document.createElement('span');value.className='ox-select-trigger__value';button.append(value);button.insertAdjacentHTML('beforeend','<svg class="ox-select-trigger__arrow" viewBox="0 0 20 20" aria-hidden="true"><path d="m6 8 4 4 4-4"/></svg>');const menu=document.createElement('div');menu.className='ox-select-menu';menu.id=`ox-select-menu-${++id}`;menu.setAttribute('role','listbox');menu.hidden=true;button.setAttribute('aria-controls',menu.id);const wrapper=document.createElement('div');wrapper.className='ox-select-wrap';const r={select,button,value,menu,wrapper,options:[],active:0,closeTimer:0,originalTab:select.getAttribute('tabindex'),originalHidden:select.getAttribute('aria-hidden'),descriptors:{}};records.set(select,r);select.insertAdjacentElement('beforebegin',wrapper);wrapper.append(select,button);(select.closest('dialog')||document.body).append(menu);select.classList.add('ox-select-native');select.tabIndex=-1;select.setAttribute('aria-hidden','true');for(const property of ['value','selectedIndex']){const native=Object.getOwnPropertyDescriptor(nativePrototype,property);r.descriptors[property]=Object.getOwnPropertyDescriptor(select,property);if(!r.descriptors[property]&&native?.get&&native?.set){Object.defineProperty(select,property,{configurable:true,enumerable:native.enumerable,get(){return native.get.call(this)},set(value){native.set.call(this,value);syncValue(r);}});}}
    button.addEventListener('focus',()=>{const box=select.getBoundingClientRect();if(box.top<0||box.bottom>innerHeight||box.left<0||box.right>innerWidth){select.scrollIntoView({block:'nearest',inline:'nearest'});update(r);}});button.addEventListener('click',()=>{openRecord===r?close(r,true):open(r)});button.addEventListener('keydown',event=>keydown(r,event));r.change=()=>{syncValue(r);enqueue()};r.focus=()=>button.focus({preventScroll:true});r.click=event=>{event.preventDefault();open(r)};r.invalid=event=>{event.preventDefault();button.setAttribute('aria-invalid','true');button.focus();};select.addEventListener('change',r.change);select.addEventListener('input',r.change);select.addEventListener('focus',r.focus);select.addEventListener('click',r.click);select.addEventListener('invalid',r.invalid);resize.observe(select);update(r);}
  function remove(r){close(r,false);clearTimeout(r.closeTimer);resize.unobserve(r.select);r.button.remove();r.menu.remove();if(r.wrapper.isConnected&&r.select.parentElement===r.wrapper)r.wrapper.replaceWith(r.select);else r.wrapper.remove();r.select.classList.remove('ox-select-native');for(const [attribute,value] of [['tabindex',r.originalTab],['aria-hidden',r.originalHidden]])value===null?r.select.removeAttribute(attribute):r.select.setAttribute(attribute,value);for(const [property,descriptor] of Object.entries(r.descriptors)){if(descriptor)Object.defineProperty(r.select,property,descriptor);else delete r.select[property];}r.select.removeEventListener('change',r.change);r.select.removeEventListener('input',r.change);r.select.removeEventListener('focus',r.focus);r.select.removeEventListener('click',r.click);r.select.removeEventListener('invalid',r.invalid);records.delete(r.select);}
  function scan(){for(const r of records.values())if(!r.select.isConnected||!r.select.matches(selector)||r.select.multiple||r.select.size>1)remove(r);document.querySelectorAll(selector).forEach(enhance);if(openRecord){populate(openRecord);setActive(openRecord,Math.max(firstEnabled(openRecord),Math.min(openRecord.active,openRecord.select.options.length-1)),false);}}
  const resize=new ResizeObserver(()=>enqueue());
  const observer=new MutationObserver(changes=>{let relevant=false;for(const change of changes){if(owned(change.target))continue;if(change.type==='childList'&&[...change.addedNodes,...change.removedNodes].every(owned))continue;relevant=true;break;}if(relevant)enqueue(true);});
  function start(){scan();observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['disabled','selected','label','hidden','multiple','size','data-theme','aria-label','aria-labelledby','aria-describedby','aria-invalid','required']});document.addEventListener('pointerdown',event=>{if(openRecord&&!openRecord.button.contains(event.target)&&!openRecord.menu.contains(event.target))close(openRecord,false);},true);document.addEventListener('reset',()=>setTimeout(()=>enqueue(),0));document.addEventListener('scroll',()=>enqueue(),true);window.addEventListener('resize',()=>enqueue());window.visualViewport?.addEventListener('resize',()=>enqueue());window.visualViewport?.addEventListener('scroll',()=>enqueue());document.fonts?.ready.then(()=>enqueue());}
  document.addEventListener('openx:motion-preference',event=>{forcedReduction=event.detail?.reduce===true;for(const r of records.values()){r.button.dataset.reduced=String(reduced());r.menu.dataset.reduced=String(reduced());if(reduced()){if(r.menu.dataset.state==='closing'){clearTimeout(r.closeTimer);r.menu.hidden=true;}else if(r===openRecord)r.menu.dataset.state='open';}}});
  window.OpenXSelectMenu={refresh:()=>enqueue(true),close:()=>close(openRecord,false)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
